#!/bin/bash

RED='\033[0;31m'
LIGHT_BLUE='\033[1;34m'
NC='\033[0m' # No color
ERROR="${RED}Incorrect inputs. Try again."

HELP_MSG=""

if [ -z "$*" ]; then
	echo "$ERROR"
	exit 1
else
	mkdir $1 && cd $1
fi
